export default {
	APP_NAME: '知心陪诊',

	// API版本
	API_LEVEL: 1,
	API_VERSION: '1.0.0',
	API_KEY: '421jOyGxfvxvKY6O',

	// 错误码
	ERROR_OK: 0,
	ERROR_NO_LOGIN: 106, // 未登录
	
	// 10-未确认,20-已确认、待付款,25-待发货,30-已发货,40-已完成,50-已取消,60-已退款,70-退款中
	HEALTH_ASSISTANT_ORDER_STATUS_UNCONFIRMED : 10,
	HEALTH_ASSISTANT_ORDER_STATUS_CONFIRMED : 20,
	HEALTH_ASSISTANT_ORDER_STATUS_WAIT_SHIP : 25,
	HEALTH_ASSISTANT_ORDER_STATUS_SHIPPED : 30,
	HEALTH_ASSISTANT_ORDER_STATUS_FINISHED : 40,
	HEALTH_ASSISTANT_ORDER_STATUS_CANCELLED : 50,
	HEALTH_ASSISTANT_ORDER_STATUS_REFUNDED : 60,
	HEALTH_ASSISTANT_ORDER_STATUS_REFUNDING : 70,
	HEALTH_ASSISTANT_ORDER_STATUS_ACTING : 80, // 服务中
	
	// 配送方式 10-线下服务；20-物流配送
	HEALTH_ASSISTANT_ORDER_SHIPPING_TYPE_OFFLINE : 10,
	HEALTH_ASSISTANT_ORDER_SHIPPING_TYPE_EXPRESS : 20,
	
	HEALTH_ASSISTANT_STATUS_WAIT_AUDIT : 0,    // 待审核
	HEALTH_ASSISTANT_STATUS_AUDIT_PASS : 1,    // 通过审核
	HEALTH_ASSISTANT_STATUS_AUDIT_REJECT : 2,    // 申请被拒绝
}
